### ISSUE TITLE
Having to login on (almost) every visit

### ISSUE THREAD

**Issue by goldylucks** [mshwery/minimalist#103]
This app is AMAZING :rocket: 

The one thing that bothers me is that I have to relogin on almost every visit.

Happy to submit a PR with some guidance.

Btw, there's no donate button!

**Comment by mshwery** [comment]
Interesting. What's your device/browser?

BTW this isn't the same repo as the production app (private repo). This is the original version.

**Comment by goldylucks** [comment]
Using chrome, on linux (ubuntu 20.04), Lenovo x1c6

**Comment by mshwery** [comment]
@goldylucks i extended the session expiration. it was 24 hours, now it's 7 days, so hopefully that will be less often for you!
