### ISSUE TITLE
Google sign in Authorization Error

### ISSUE THREAD

**Issue by adithyarao3103** [mshwery/minimalist#104]
Trying to sign in with Google throws up the Authorization Error **_Error 400: redirect_uri_mismatch_** 

The attached screenshot has the complete details
![image](https://user-images.githubusercontent.com/64120705/166094790-90d368e1-eb63-48e7-b897-7ecbf09f28b5.png)

**Comment by mshwery** [comment]
This is not the same project.

Also, you must use https! http won't work (as you've discovered)
