### ISSUE TITLE
List share email has a link to beta.getminimalist.com which no longer resolves

### ISSUE THREAD

**Issue by francisli** [mshwery/minimalist#105]
Hi there, I don't know if you still have time to maintain this lovely web app, but I just tried sharing a list, and the link in the share email (after redirecting through the mail tracker link) points to `https://beta.getminimalist.com/lists/<list id>` which no longer resolves.

**Comment by mshwery** [comment]
Thanks for reporting! I've fixed this. You can simply change the `beta` part of the url to `www` instead.
